Create diagram using Highcharts (#382)
* File Upload widget

Using 'Attachment API - POST /now/attachment/file' to upload multiple files on form submit.

* Upload file widget

This widget is using the 'Attachment API - POST /now/attachment/file' to upload multiple files on form submit.

The result will appear in the console or check directly the record.

* Creating Process flow in service portal

In this snippet you will create a custom process flow with a custom page and populated with standard widgets.

* Remove

* Revert "Remove"

This reverts commit 22fbfc32e5a65e062a298865c4d157cc02f2ea8e.

* Revert "Creating Process flow in service portal"

This reverts commit c45dde482eb98f65807165249973ff937fb484d3.

* Record process flow

Record process flow

* Delete UI Actions/Add "Show Workflow" Related link directory

* Correct folder name

This change will correct an issue which prevent window users to clone this repo.

Error
error: invalid path 'UI Actions/Add "Show Workflow" Related link/readme.md'

* Force to Update Set

* Update repo

* Force to Update Set

* Update readme.md

* Creating diagram using GoJS library

Creating diagram using GoJS library

* Update readme.md

* Update readme.md

* Create diagram using Highcharts

Update folder name for GoJS
Create diagram using Highcharts